apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo-spring-app
          ports:
            - containerPort: 8080
            - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: debugger
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
