apiVersion: v1
kind: Service
metadata:
  name: svelte-service
spec:
  type: ClusterIP
  selector:
    app: svelte
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svelte
  template:
    metadata:
      labels:
        app: svelte
    spec:
      containers:
        - name: svelte
          image: glad2os/svelte
          ports:
            - containerPort: 80
