apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: demo-spring-app
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
  - resourceType: service
    resourceName: demo-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: demo-service
    port: 5050
    localPort: 5050
  - resourceType: service
    resourceName: mongodb
    port: 27017
