apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
    - image: glad2os/demo-spring-app
      context: .
      jib: {}
    - image: glad2os/svelte
      context: svelte
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
  - resourceType: service
    resourceName: demo-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: demo-service
    port: 5050
    localPort: 5050
  - resourceType: service
    resourceName: mongodb
    port: 27017
  - resourceType: service
    resourceName: svelte-service
    port: 80
    localPort: 5173